Repository AArnott/Nerdbank.MessagePack, pull requests merged in 2024-12, with the labels that each got.

#139 Add option to serialize enums by name
  src/Nerdbank.MessagePack/Converters/EnumAsOrdinalConverter`2.cs
  src/Nerdbank.MessagePack/Converters/EnumAsStringConverter`2.cs
  src/Nerdbank.MessagePack/MessagePackSerializer.cs
  src/Nerdbank.MessagePack/PublicAPI.Unshipped.txt
  src/Nerdbank.MessagePack/StandardVisitor.cs
  src/Nerdbank.MessagePack/StringEncoding.cs
  test/Nerdbank.MessagePack.Tests/EnumTests.cs
Labels: enhancement

#141 Run analyzers on main library
  src/Nerdbank.MessagePack.Analyzers/ConverterAnalyzers.cs
  src/Nerdbank.MessagePack.Analyzers/ReferenceSymbols.cs
  src/Nerdbank.MessagePack/Converters/ArrayWithNestedDimensionsConverter`2.cs
  src/Nerdbank.MessagePack/Converters/DictionaryConverter`3.cs
  src/Nerdbank.MessagePack/Converters/EnumerableConverter`2.cs
  src/Nerdbank.MessagePack/Converters/ObjectArrayConverter`1.cs
  src/Nerdbank.MessagePack/Converters/ObjectMapConverter`1.cs
  src/Nerdbank.MessagePack/Converters/SubTypeUnionConverter`1.cs
  src/Nerdbank.MessagePack/IMessagePackConverter.cs
  src/Nerdbank.MessagePack/MessagePackConverter`1.cs
  src/Nerdbank.MessagePack/Nerdbank.MessagePack.csproj
  src/Nerdbank.MessagePack/ReferencePreservingConverter`1.cs
  test/Nerdbank.MessagePack.Analyzers.Tests/ConverterAnalyzersTests.cs
Labels: analyzers

#134 Add method to export a JSON schema for a given type shape
  Directory.Packages.props
  docfx/analyzers/NBMsgPack032.md
  docfx/analyzers/index.md
  docfx/analyzers/toc.yml
  docfx/docs/custom-converters.md
  docfx/docs/customizing-serialization.md
  docfx/docs/migrating.md
  src/.editorconfig
  src/Nerdbank.MessagePack.Analyzers/AnalyzerReleases.Unshipped.md
  src/Nerdbank.MessagePack.Analyzers/ConverterAnalyzers.cs
  src/Nerdbank.MessagePack.Analyzers/Strings.resx
  src/Nerdbank.MessagePack/Converters/ArrayConverter`1.cs
  src/Nerdbank.MessagePack/Converters/ArrayWithFlattenedDimensionsConverter`2.cs
  src/Nerdbank.MessagePack/Converters/ArrayWithNestedDimensionsConverter`2.cs
  src/Nerdbank.MessagePack/Converters/ArraysOfPrimitivesConverters.Generated.cs
  src/Nerdbank.MessagePack/Converters/ArraysOfPrimitivesConverters.Generated.tt
  src/Nerdbank.MessagePack/Converters/CommonRecords.cs
  src/Nerdbank.MessagePack/Converters/DelayedConverterFactory.cs
  src/Nerdbank.MessagePack/Converters/DictionaryConverter`3.cs
  src/Nerdbank.MessagePack/Converters/EnumAsOrdinalConverter`2.cs
  src/Nerdbank.MessagePack/Converters/EnumAsStringConverter`2.cs
  src/Nerdbank.MessagePack/Converters/EnumerableConverter`2.cs
  src/Nerdbank.MessagePack/Converters/HardwareAccelerated.cs
  src/Nerdbank.MessagePack/Converters/IntConverters.cs
  src/Nerdbank.MessagePack/Converters/IntConverters.tt
  src/Nerdbank.MessagePack/Converters/ObjectArrayConverter`1.cs
  src/Nerdbank.MessagePack/Converters/ObjectConverterBase`1.cs
  src/Nerdbank.MessagePack/Converters/ObjectMapConverter`1.cs
  src/Nerdbank.MessagePack/Converters/PrimitiveConverters.cs
  src/Nerdbank.MessagePack/Converters/RawMessagePackConverter.cs
  src/Nerdbank.MessagePack/Converters/SubTypeUnionConverter`1.cs
  src/Nerdbank.MessagePack/IMessagePackConverter.cs
  src/Nerdbank.MessagePack/JsonSchemaContext.cs
  src/Nerdbank.MessagePack/MessagePackConverter`1.cs
  src/Nerdbank.MessagePack/MessagePackSerializer.GetSchema.cs
  src/Nerdbank.MessagePack/MessagePackSerializer.cs
  src/Nerdbank.MessagePack/PublicAPI.Unshipped.txt
  src/Nerdbank.MessagePack/ReferencePreservingConverter`1.cs
  src/Nerdbank.MessagePack/StandardVisitor.cs
  test/Nerdbank.MessagePack.Analyzers.Tests/ConverterAnalyzersTests.cs
  test/Nerdbank.MessagePack.Tests/Nerdbank.MessagePack.Tests.csproj
  test/Nerdbank.MessagePack.Tests/Resources/KnownGoodSchemas/BasicObject_Key.schema.json
  test/Nerdbank.MessagePack.Tests/Resources/KnownGoodSchemas/BasicObject_Map.schema.json
  test/Nerdbank.MessagePack.Tests/Resources/KnownGoodSchemas/BasicObject_Map_NamingPolicy.schema.json
  test/Nerdbank.MessagePack.Tests/Resources/KnownGoodSchemas/Complex.schema.json
  test/Nerdbank.MessagePack.Tests/Resources/KnownGoodSchemas/CustomConverterHasUndocumentedSchema.schema.json
  test/Nerdbank.MessagePack.Tests/Resources/KnownGoodSchemas/CustomConverterWithDocumentedSchema.schema.json
  test/Nerdbank.MessagePack.Tests/Resources/KnownGoodSchemas/DateTimeExtension.schema.json
  test/Nerdbank.MessagePack.Tests/Resources/KnownGoodSchemas/Recursive.schema.json
  test/Nerdbank.MessagePack.Tests/Resources/KnownGoodSchemas/SubTypeSchema.schema.json
  test/Nerdbank.MessagePack.Tests/SchemaTests.cs
Labels: enhancement

#140 SIMD acceleration for float/double[]
  src/Nerdbank.MessagePack/Converters/HardwareAccelerated.cs
Labels: enhancement

#144 Add support for string interning
  Directory.Packages.props
  src/Nerdbank.MessagePack/Converters/PrimitiveConverters.cs
  src/Nerdbank.MessagePack/MessagePackSerializer.cs
  src/Nerdbank.MessagePack/Nerdbank.MessagePack.csproj
  src/Nerdbank.MessagePack/PublicAPI.Unshipped.txt
  src/Nerdbank.MessagePack/ReferenceEqualityTracker.cs
  src/Nerdbank.MessagePack/StandardVisitor.cs
  test/Benchmarks/StringInterning.cs
  test/Nerdbank.MessagePack.Tests/ReferencePreservationTests.cs
  test/Nerdbank.MessagePack.Tests/StringInterningTests.cs
Labels: enhancement

#130 Improve performance of async deserialization
  samples/.editorconfig
  samples/CustomConverters.cs
  src/Nerdbank.MessagePack.Analyzers/ConverterAnalyzers.cs
  src/Nerdbank.MessagePack/Converters/ArrayConverter`1.cs
  src/Nerdbank.MessagePack/Converters/DictionaryConverter`3.cs
  src/Nerdbank.MessagePack/Converters/EnumerableConverter`2.cs
  src/Nerdbank.MessagePack/Converters/ObjectArrayConverter`1.cs
  src/Nerdbank.MessagePack/Converters/ObjectArrayWithNonDefaultCtorConverter`2.cs
  src/Nerdbank.MessagePack/Converters/ObjectMapConverter`1.cs
  src/Nerdbank.MessagePack/Converters/ObjectMapWithNonDefaultCtorConverter`2.cs
  src/Nerdbank.MessagePack/DecodeResultExtensions.cs
  src/Nerdbank.MessagePack/MessagePackAsyncReader.cs
  src/Nerdbank.MessagePack/MessagePackConverter`1.cs
  src/Nerdbank.MessagePack/MessagePackPrimitives.Writers.cs
  src/Nerdbank.MessagePack/MessagePackReader.Integers.cs
  src/Nerdbank.MessagePack/MessagePackReader.Integers.tt
  src/Nerdbank.MessagePack/MessagePackReader.cs
  src/Nerdbank.MessagePack/MessagePackSerializer.cs
  src/Nerdbank.MessagePack/MessagePackStreamingReader.Integers.cs
  src/Nerdbank.MessagePack/MessagePackStreamingReader.Integers.tt
  src/Nerdbank.MessagePack/MessagePackStreamingReader.cs
  src/Nerdbank.MessagePack/Nerdbank.MessagePack.csproj
  src/Nerdbank.MessagePack/SequenceReader`1.cs
  src/Nerdbank.MessagePack/StandardVisitor.cs
  src/Nerdbank.MessagePack/net8.0/PublicAPI.Unshipped.txt
  src/Nerdbank.MessagePack/netstandard2.0/PublicAPI.Unshipped.txt
  test/Nerdbank.MessagePack.Tests/MessagePackStreamingReaderTests.cs
Labels: enhancement

#156 Implement stateful, incremental skip
  samples/CustomConverters.cs
  src/Nerdbank.MessagePack/Converters/ObjectMapConverter`1.cs
  src/Nerdbank.MessagePack/Converters/ObjectMapWithNonDefaultCtorConverter`2.cs
  src/Nerdbank.MessagePack/MessagePackAsyncReader.cs
  src/Nerdbank.MessagePack/MessagePackReader.cs
  src/Nerdbank.MessagePack/MessagePackStreamingReader.cs
  src/Nerdbank.MessagePack/SerializationContext.cs
  src/Nerdbank.MessagePack/net8.0/PublicAPI.Unshipped.txt
  src/Nerdbank.MessagePack/netstandard2.0/PublicAPI.Unshipped.txt
  test/Nerdbank.MessagePack.Tests/MessagePackStreamingReaderTests.cs
Labels: enhancement

#159 Add `MessagePackSerializer.MaxAsyncBuffer` to speed up small async deserializations
  src/Nerdbank.MessagePack/MessagePackSerializer.cs
  src/Nerdbank.MessagePack/net8.0/PublicAPI.Unshipped.txt
  src/Nerdbank.MessagePack/netstandard2.0/PublicAPI.Unshipped.txt
  test/Nerdbank.MessagePack.Tests/AsyncSerializationTests.cs
  test/Nerdbank.MessagePack.Tests/FragmentedPipeReader.cs
  test/Nerdbank.MessagePack.Tests/MessagePackAsyncReaderTests.cs
  test/Nerdbank.MessagePack.Tests/MessagePackSerializerTestBase.cs
  test/Nerdbank.MessagePack.Tests/ObjectsAsArraysTests.cs
Labels: enhancement

#161 Add NBMsgPack033 - NBMsgPack037 analyzers
  .github/workflows/build.yml
  docfx/analyzers/NBMsgPack033.md
  docfx/analyzers/NBMsgPack034.md
  docfx/analyzers/NBMsgPack035.md
  docfx/analyzers/NBMsgPack036.md
  docfx/analyzers/NBMsgPack037.md
  docfx/analyzers/index.md
  docfx/analyzers/toc.yml
  samples/.editorconfig
  samples/AnalyzerDocs/NBMsgPack033.cs
  samples/AnalyzerDocs/NBMsgPack034.cs
  samples/AnalyzerDocs/NBMsgPack035.cs
  samples/AnalyzerDocs/NBMsgPack036.cs
  samples/AnalyzerDocs/NBMsgPack037.cs
  samples/CustomConverters.cs
  src/Analyzers.props
  src/Nerdbank.MessagePack.Analyzers/AnalyzerReleases.Unshipped.md
  src/Nerdbank.MessagePack.Analyzers/ConverterAnalyzers.cs
  src/Nerdbank.MessagePack.Analyzers/Strings.resx
  src/Nerdbank.MessagePack/Converters/ArrayConverter`1.cs
  src/Nerdbank.MessagePack/Converters/DictionaryConverter`3.cs
  src/Nerdbank.MessagePack/Converters/ObjectArrayConverter`1.cs
  src/Nerdbank.MessagePack/Converters/ObjectMapConverter`1.cs
  src/Nerdbank.MessagePack/Converters/ObjectMapWithNonDefaultCtorConverter`2.cs
  test/Nerdbank.MessagePack.Analyzers.Tests/ConverterAnalyzersTests.cs
  test/Nerdbank.MessagePack.Analyzers.Tests/Verifiers/CodeFixVerifier`2.cs
Labels: enhancement, analyzers

#162 Add SerializationConstructorAttribute migration analyzer
  docfx/analyzers/NBMsgPack106.md
  docfx/analyzers/index.md
  docfx/analyzers/toc.yml
  src/Nerdbank.MessagePack.Analyzers.CodeFixes/MigrationCodeFix.cs
  src/Nerdbank.MessagePack.Analyzers/AnalyzerReleases.Unshipped.md
  src/Nerdbank.MessagePack.Analyzers/MessagePackCSharpReferenceSymbols.cs
  src/Nerdbank.MessagePack.Analyzers/MigrationAnalyzer.cs
  src/Nerdbank.MessagePack.Analyzers/Strings.resx
  test/Nerdbank.MessagePack.Analyzers.Tests/MigrationAnalyzerTests.cs
Labels: enhancement, analyzers

#166 Add analyzer to flag missing `ref` modifier on ref struct typed parameters
  docfx/analyzers/NBMsgPack050.md
  docfx/analyzers/index.md
  docfx/analyzers/toc.yml
  samples/AnalyzerDocs/NBMsgPack050.cs
  src/Nerdbank.MessagePack.Analyzers/AnalyzerReleases.Unshipped.md
  src/Nerdbank.MessagePack.Analyzers/RefParametersForRefStructsAnalyzer.cs
  src/Nerdbank.MessagePack.Analyzers/ReferenceSymbols.cs
  src/Nerdbank.MessagePack.Analyzers/Strings.resx
  src/Nerdbank.MessagePack/Converters/ArrayWithNestedDimensionsConverter`2.cs
  test/Nerdbank.MessagePack.Analyzers.Tests/RefParametersForRefStructsAnalyzerTests.cs
Labels: enhancement, analyzers

#167 Improve known sub-type support
  docfx/docs/migrating.md
  docfx/docs/unions.md
  samples/Unions.cs
  src/Nerdbank.MessagePack.Analyzers/AnalyzerUtilities.cs
  src/Nerdbank.MessagePack.Analyzers/KnownSubTypeAnalyzers.cs
  src/Nerdbank.MessagePack/Converters/CommonRecords.cs
  src/Nerdbank.MessagePack/Converters/ObjectMapConverter`1.cs
  src/Nerdbank.MessagePack/Converters/ObjectMapWithNonDefaultCtorConverter`2.cs
  src/Nerdbank.MessagePack/Converters/SubTypeUnionConverter`1.cs
  src/Nerdbank.MessagePack/IKnownSubTypeMapping.cs
  src/Nerdbank.MessagePack/KnownSubTypeAttribute.cs
  src/Nerdbank.MessagePack/KnownSubTypeMapping`1.cs
  src/Nerdbank.MessagePack/MessagePackSerializer.cs
  src/Nerdbank.MessagePack/StandardVisitor.cs
  src/Nerdbank.MessagePack/StringEncoding.cs
  src/Nerdbank.MessagePack/SubTypeAlias.cs
  src/Nerdbank.MessagePack/net8.0/PublicAPI.Unshipped.txt
  src/Nerdbank.MessagePack/netstandard2.0/PublicAPI.Unshipped.txt
  test/Nerdbank.MessagePack.Analyzers.Tests/KnownSubTypeAnalyzersTests.cs
  test/Nerdbank.MessagePack.Tests/KnownSubTypeMappingTests.cs
  test/Nerdbank.MessagePack.Tests/KnownSubTypeTests.cs
  test/Nerdbank.MessagePack.Tests/ReferencePreservationTests.cs
  test/Nerdbank.MessagePack.Tests/SchemaTests.cs
Labels: enhancement

#187 Add MessagePackString class
  docfx/docs/custom-converters.md
  samples/CustomConverters.cs
  src/Nerdbank.MessagePack/MessagePackReader.cs
  src/Nerdbank.MessagePack/MessagePackString.cs
  src/Nerdbank.MessagePack/net8.0/PublicAPI.Unshipped.txt
  src/Nerdbank.MessagePack/netstandard2.0/PublicAPI.Unshipped.txt
  test/Nerdbank.MessagePack.Tests/MessagePackReaderTests.cs
  test/Nerdbank.MessagePack.Tests/MessagePackStringTests.cs
Labels: enhancement

#199 Add friendlier `MessagePackWriter.Write(MessagePackString)` method
  samples/CustomConverters.cs
  src/Nerdbank.MessagePack/MessagePackWriter.cs
  src/Nerdbank.MessagePack/net8.0/PublicAPI.Unshipped.txt
  src/Nerdbank.MessagePack/netstandard2.0/PublicAPI.Unshipped.txt
  test/Nerdbank.MessagePack.Tests/MessagePackWriterTests.cs
Labels: enhancement
